%function reloadGUINotPaired

%function to reload the GUI for udp for the not paired configuration
%ASM 5/2012

function reloadGUINotPaired(src,evnt)
    
    global guiText;
    
    if guiText.config == 1
        return;
    end
    
    stopLiveDataAq();
    
    if guiText.config == 2
        delete(guiText.text1,guiText.text2,guiText.text3,guiText.text4,guiText.text5,guiText.text6,guiText.text7,...
            guiText.timeText,guiText.trialTextTower,guiText.rewardTextTower,guiText.trialTextNoTower,guiText.rewardTextNoTower,...
            guiText.percCorrTextTower,guiText.percCorrTextNoTower,guiText.start,guiText.stop,guiText.sessionTime,...
            guiText.sessionTimeText);
    elseif guiText.config == 3
        delete(guiText.text1,guiText.text2,guiText.text3,guiText.text4,guiText.text5,guiText.text6,guiText.text7,...
            guiText.text8,guiText.timeText,guiText.start,guiText.stop,guiText.sessionTime,guiText.sessionTimeText,...
            guiText.trialTextTotal,guiText.rewardTextTotal,guiText.percCorrTextTotal,guiText.trialTextDelay,...
            guiText.percDelay,guiText.rewardTextDelay,guiText.percCorrTextDelay);
    end
    
    guiText.config = 1;
    
    scrn = get(0,'screensize');
    set(guiText.figHandle,'OuterPosition',[.8*scrn(3) .35*scrn(4) .2*scrn(3) .3*scrn(4)]);
    
    guiText.text1 = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.1 .8 .6 .1],'String','Time Elapsed:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.text2 = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 1],'Units','Normalized',...
        'Position',[.1 .65 .6 .1],'String','Number of Trials:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.text3 = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.87 0.49 0],'Units','Normalized',...
        'Position',[.1 .5 .6 .1],'String','Number of Rewards:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.text4 = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.23 0.44 .34],'Units','Normalized',...
        'Position',[.1 .35 .6 .1],'String','Percent Correct:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);

    guiText.timeText = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.65 .8 .25 .1],'String','00:00:00','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.trialText = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 1],'Units','Normalized',...
        'Position',[.7 .65 .2 .1],'String','0','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.rewardText = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.87 0.49 0],'Units','Normalized',...
        'Position',[.7 .5 .2 .1],'String','0','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.percCorrText = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.23 0.44 .34],'Units','Normalized',...
        'Position',[.7 .35 .2 .1],'String','0%','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);

    guiText.start = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.05 .05 .425 .12],'String','Start','Style','pushbutton','BackgroundColor',[0.7969 0.7969 0.7969],...
        'Callback',@startLiveDataAqID1);
    guiText.stop = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.525 .05 .425 .12],'String','Stop','Style','pushbutton','BackgroundColor',[0.7969 0.7969 0.7969],...
        'Callback',@stopLiveDataAq);
    guiText.sessionTime = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.5 .2 .45 .12],'String','00:45:00','Style','edit');
    guiText.sessionTimeText = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.05 .2 .4 .1],'String','Session Time:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);

end