%function reloadGUIPaired

%function to reload the GUI for udp for the paired configuration
%ASM 5/2012

function reloadGUIPaired(src,evnt)
    
    global guiText;
    
    if guiText.config == 2
        return;
    end
    
    stopLiveDataAq();
    
    if guiText.config == 1
        delete(guiText.text1,guiText.text2,guiText.text3,guiText.text4,guiText.timeText,guiText.start,...
            guiText.stop,guiText.sessionTime,guiText.trialText,guiText.rewardText,guiText.percCorrText,...
            guiText.sessionTimeText);
    elseif guiText.config == 3
        delete(guiText.text1,guiText.text2,guiText.text3,guiText.text4,guiText.text5,guiText.text6,guiText.text7,...
            guiText.text8,guiText.timeText,guiText.start,guiText.stop,guiText.sessionTime,guiText.sessionTimeText,...
            guiText.trialTextTotal,guiText.rewardTextTotal,guiText.percCorrTextTotal,guiText.trialTextDelay,...
            guiText.percDelay,guiText.rewardTextDelay,guiText.percCorrTextDelay);
    end
    
    guiText.config = 2;
    
    scrn = get(0,'screensize');
    set(guiText.figHandle,'OuterPosition',[.75*scrn(3) .25*scrn(4) .25*scrn(3) .5*scrn(4)]);
    
    guiText.text1 = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.1 .88 .6 .06],'String','Time Elapsed:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.text2 = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 1],'Units','Normalized',...
        'Position',[.1 .79 .6 .06],'String','Number of Tower Trials:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.text3 = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.87 0.49 0],'Units','Normalized',...
        'Position',[.1 .7 .6 .06],'String','Number of Tower Rewards:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.text4 = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.23 0.44 .34],'Units','Normalized',...
        'Position',[.1 .61 .6 .06],'String','Percent Correct Tower:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.text5 = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[ 0.49 0.15 0.8],'Units','Normalized',...
        'Position',[.1 .52 .6 .06],'String','Number of No Tower Trials:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.text6 = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.39 0.5 1],'Units','Normalized',...
        'Position',[.05 .43 .65 .06],'String','Number of No Tower Rewards:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.text7 = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.55 0.27 .07],'Units','Normalized',...
        'Position',[.1 .34 .6 .06],'String','Percent Correct No Tower:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);

    guiText.timeText = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.65 .88 .25 .06],'String','00:00:00','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.trialTextTower = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 1],'Units','Normalized',...
        'Position',[.7 .79 .2 .06],'String','0','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.rewardTextTower = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.87 0.49 0],'Units','Normalized',...
        'Position',[.7 .7 .2 .06],'String','0','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.percCorrTextTower = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.23 0.44 .34],'Units','Normalized',...
        'Position',[.7 .61 .2 .06],'String','0%','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.trialTextNoTower = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.49 .15 .8],'Units','Normalized',...
        'Position',[.7 .52 .2 .06],'String','0','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.rewardTextNoTower = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.39 0.5 1],'Units','Normalized',...
        'Position',[.7 .43 .2 .06],'String','0','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);
    guiText.percCorrTextNoTower = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0.55 0.27 .07],'Units','Normalized',...
        'Position',[.7 .34 .2 .06],'String','0%','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);

    guiText.start = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.05 .05 .425 .12],'String','Start','Style','pushbutton','BackgroundColor',[0.7969 0.7969 0.7969],...
        'Callback',@startLiveDataAqID2);
    guiText.stop = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.525 .05 .425 .12],'String','Stop','Style','pushbutton','BackgroundColor',[0.7969 0.7969 0.7969],...
        'Callback',@stopLiveDataAq);
    guiText.sessionTime = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.5 .2 .45 .12],'String','00:45:00','Style','edit');
    guiText.sessionTimeText = uicontrol('FontName','Arial','FontSize',15,'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
        'Position',[.05 .2 .4 .1],'String','Session Time:','Style','text','BackgroundColor',[0.7969 0.7969 0.7969]);

end